PD-5964 PD-5963 PD-5958  PD-5956 PD-5955 PD-5957 Transactional fixes for various managers  (#7584)
* PD-5955 Fixed jakarta.persistence.TransactionRequiredException

Fixed jakarta.persistence.TransactionRequiredException: Executing an update/delete query] with root cause
jakarta.persistence.TransactionRequiredException: Executing an update/delete query in the ProfileEntityManager and other places with potentially the same issue

* PD-5956 Fixed transactional for enable, disable development tools

* PD-5958 PD-5963 PD-5964 more transactional fizes

* Added the transaction template mock